### PR TITLE
add missing header for PRIu32 and PRIu16 macros

### PR DESCRIPTION
**Pull request by squizz617**
Build fails with the following message:
```
Starting >>> px4_ros_com                                                                                                                                                                                                                                                                  
--- stderr: px4_ros_com                                                                                                                                                                                                                                                                   
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp: In member function ‘ssize_t Transport_node::read(uint8_t*, char*, size_t)’:                                                                                    
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:153:99: error: expected ‘)’ before ‘PRIu32’                                                                                                                     
  153 |   if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓↓ %" PRIu32 ")\033[0m\n", msg_start_pos);                                                                                                                                               
      |                    ~                                                                              ^~~~~~~                                                                                                                                                                         
      |                                                                                                   )                                                                                                                                                                               
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:153:97: warning: spurious trailing ‘%’ in format [-Wformat=]                                                                                                    
  153 |   if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓↓ %" PRIu32 ")\033[0m\n", msg_start_pos);                                                                                                                                               
      |                                                                                                 ^                                                                                                                                                                                 
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:153:21: warning: too many arguments for format [-Wformat-extra-args]                                                                                            
  153 |   if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓↓ %" PRIu32 ")\033[0m\n", msg_start_pos);                                                                                                                                               
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:181:97: error: expected ‘)’ before ‘PRIu32’                                                                                                                     
  181 |    if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓ %" PRIu32 ")\033[0m\n", msg_start_pos);                                                                                                                                               
      |                     ~                                                                           ^~~~~~~                                                                                                                                                                           
      |                                                                                                 )                                                                                                                                                                                 
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:181:95: warning: spurious trailing ‘%’ in format [-Wformat=]                                                                                                    
  181 |    if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓ %" PRIu32 ")\033[0m\n", msg_start_pos);                                                                                                                                               
      |                                                                                               ^                                                                                                                                                                                   
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:181:22: warning: too many arguments for format [-Wformat-extra-args]                                                                                            
  181 |    if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓ %" PRIu32 ")\033[0m\n", msg_start_pos);                                                                                                                                               
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                  
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:197:67: error: expected ‘)’ before ‘PRIu16’                                                                                                                     
  197 |   if (debug) printf("\033[0;31m[ micrortps_transport ]\tBad CRC %" PRIu16 " != %" PRIu16 "\t\t(↓ %lu)\033[0m\n", read_crc, calc_crc, (unsigned long)(header_size + payload_len));                                                                                                 
      |                    ~                                              ^~~~~~~                                                                                                                                                                                                         
      |                                                                   )                                                                                                                                                                                                               
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:197:65: warning: spurious trailing ‘%’ in format [-Wformat=]                                                                                                    
  197 |   if (debug) printf("\033[0;31m[ micrortps_transport ]\tBad CRC %" PRIu16 " != %" PRIu16 "\t\t(↓ %lu)\033[0m\n", read_crc, calc_crc, (unsigned long)(header_size + payload_len));                                                                                                 
      |                                                                 ^                                                                                                                                                                                                                 
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:197:21: warning: too many arguments for format [-Wformat-extra-args]                                                                                            
  197 |   if (debug) printf("\033[0;31m[ micrortps_transport ]\tBad CRC %" PRIu16 " != %" PRIu16 "\t\t(↓ %lu)\033[0m\n", read_crc, calc_crc, (unsigned long)(header_size + payload_len));                                                                                                 
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                   
make[2]: *** [CMakeFiles/micrortps_agent.dir/build.make:576: CMakeFiles/micrortps_agent.dir/src/micrortps_agent/microRTPS_transport.cpp.o] Error 1                                                                                                                                        
make[2]: *** Waiting for unfinished jobs....                                                                                                                                                                                                                                              
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/micrortps_agent.dir/all] Error 2                                                                                                                                                                                                       
make: *** [Makefile:141: all] Error 2                                                                                                        
---                                                                                                                                                                                                                                                                                       
Failed   <<< px4_ros_com [3.54s, exited with code 2]                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                          
Summary: 1 package finished [25.5s]                                                                                                                                                                                                                                                       
  1 package failed: px4_ros_com                                                                                                                                                                                                                                                           
  1 package had stderr output: px4_ros_com  
```

This PR fixes the error by including `inttypes.h` to the template file.

### CODE REVIEW

**Comment by TSC21** [comment]
@squizz617 what platform are you building this against? Which GCC?

**Comment by squizz617** [comment]
@TSC21 Using GCC 9.3.0 on Ubuntu 20.04 running kernel 5.8.0.

**Comment by TSC21** [comment]
> @TSC21 Using GCC 9.3.0 on Ubuntu 20.04 running kernel 5.8.0.

Interesting: we have the builds running in CI for a long time now and several developers building this and we never faced this issue. So my question here would be: what is different on your system that requires this header to be included?

**Comment by squizz617** [comment]
Interesting! I'm not sure what's the difference either, but will try building on another ubuntu 20.04 machine.
BTW, here's the dump of stdout. This might help finding the cause?
```
-- The C compiler identification is GNU 9.3.0                                                                                                                                                                                                                                             
-- The CXX compiler identification is GNU 9.3.0                                                                                                                                                                                                                                           
-- Check for working C compiler: /usr/bin/cc                                                                                                                                                                                                                                              
-- Check for working C compiler: /usr/bin/cc -- works                                                                                                                                                                                                                                     
-- Detecting C compiler ABI info                                                                                                                                                                                                                                                          
-- Detecting C compiler ABI info - done                                                                                                                                                                                                                                                   
-- Detecting C compile features                                                                                                                                                                                                                                                           
-- Detecting C compile features - done                                                                                                                                                                                                                                                    
-- Check for working CXX compiler: /usr/bin/c++                                                                                              
-- Check for working CXX compiler: /usr/bin/c++ -- works                                                                                     
-- Detecting CXX compiler ABI info                                                                                                                                                                                                                                                        
-- Detecting CXX compiler ABI info - done                                                                                                                                                                                                                                                 
-- Detecting CXX compile features                                                                                                                                                                                                                                                         
-- Detecting CXX compile features - done                                                                                                                                                                                                                                                  
-- Performing Test COMPILER_SUPPORTS_CXX17                                                                                                                                                                                                                                                
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success                                                                                         
-- Performing Test COMPILER_SUPPORTS_CXX14                                                                                                                                                                                                                                                
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success                                                                                         
-- Performing Test COMPILER_SUPPORTS_CXX11                                                                                                   
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success                                                                                                                                                                                                                                      
-- Performing Test COMPILER_SUPPORTS_CXX0X                                                                                                                                                                                                                                                
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success                                                                                                                                                                                                                                      
-- Using C++17 compiler                                                                                                                      
-- Found ament_cmake: 0.9.8 (/home/seulbae/workspace/ros-security/ros2_foxy/install/ament_cmake/share/ament_cmake/cmake)                                                                                                                                                                  
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3")                                                                                                                                                                                         
-- Using PYTHON_EXECUTABLE: /usr/bin/python3                                                                                                 
-- Override CMake install command with custom implementation using symlinks instead of copying resources                                                                                                                                                                                  
-- Found builtin_interfaces: 1.0.0 (/home/seulbae/workspace/ros-security/ros2_foxy/install/builtin_interfaces/share/builtin_interfaces/cmake)                                                                                                                                             
-- Using all available rosidl_typesupport_c: rosidl_typesupport_introspection_c;rosidl_typesupport_fastrtps_c                                                                                                                                                                             
-- Found rosidl_adapter: 1.2.1 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake)            
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")                                                            
-- Found FastRTPS: /home/seulbae/workspace/ros-security/ros2_foxy/install/fastrtps/include                                                                                                                                                                                                
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_introspection_cpp;rosidl_typesupport_fastrtps_cpp                          
-- Found rclcpp: 2.3.1 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rclcpp/share/rclcpp/cmake)                                                                                                                                                                                 
-- Found rmw_implementation_cmake: 1.0.3 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rmw_implementation_cmake/share/rmw_implementation_cmake/cmake)                                                                                                                           
-- Using RMW implementation 'rmw_fastrtps_cpp' as default                                                                                    
-- Looking for pthread.h                                                                                                                     
-- Looking for pthread.h - found                                                                                                             
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD                                                                                                   
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed                                                                                                                                                                                                                                       
-- Looking for pthread_create in pthreads                                                                                                    
-- Looking for pthread_create in pthreads - not found                                                                                                                                                                                                                                     
-- Looking for pthread_create in pthread                                                                                                     
-- Looking for pthread_create in pthread - found                                                                                             
-- Found Threads: TRUE                                                                                                                                                                                                                                                                    
-- Found rmw_fastrtps_cpp: 1.2.5 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rmw_fastrtps_cpp/share/rmw_fastrtps_cpp/cmake)                                                                                                                                                   
-- Found px4_msgs: 2.0.1 (/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/cmake)               
-- Found sensor_msgs: 2.0.4 (/home/seulbae/workspace/ros-security/ros2_foxy/install/sensor_msgs/share/sensor_msgs/cmake)                                                                                                                                                                  
-- Found eigen3_cmake_module: 0.1.1 (/home/seulbae/workspace/ros-security/ros2_foxy/install/eigen3_cmake_module/share/eigen3_cmake_module/cmake)                                                                                                                                          
-- fastrtpsgen found in /usr/local/bin                                                                                                                                                                                                                                                    
openjdk version "11.0.11" 2021-04-20                                                                                                                                                                                                                                                      
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)                                                                                                                                                                                                                       
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)                                                        
-- fastrtpsgen version 1.0.4                                                                                                                                                                                                                                                              
-- px4_msgs message dir under /home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg              
-- IDL definitions under /home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg                                                                                                                                                                
-- Retrieving list of msgs to send...                                                                                                                                                                                                                                                     
-- List of msgs to send: DebugArray, DebugKeyValue, DebugValue, DebugVect, OffboardControlMode, OpticalFlow, PositionSetpoint, PositionSetpointTriplet, TelemetryStatus, Timesync, TrajectoryWaypoint, VehicleCommand, VehicleLocalPositionSetpoint, VehicleTrajectoryWaypoint, OnboardCom
puterStatus, TrajectoryBezier, VehicleTrajectoryBezier, VehicleMocapOdometry, VehicleVisualOdometry, TrajectorySetpoint                                                                                                                                                                   
-- Retrieving list of msgs to receive...                                                                                                     
-- List of msgs to receive: InputRc, SatelliteInfo, SensorCombined, Timesync, TrajectoryWaypoint, VehicleAttitude, VehicleControlMode, VehicleLocalPosition, VehicleOdometry, VehicleStatus, CollisionConstraints, VehicleAngularVelocity                                                 
-- Configuring done                                                                                                                                                                                                                                                                       
-- Generating done                                                                                                                           
-- Build files have been written to: /home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/build/px4_ros_com  
```

**Comment by TSC21** [comment]
> Interesting! I'm not sure what's the difference either, but will try building on another ubuntu 20.04 machine.
> BTW, here's the dump of stdout. This might help finding the cause?
> 
> ```
> -- The C compiler identification is GNU 9.3.0                                                                                                                                                                                                                                             
> -- The CXX compiler identification is GNU 9.3.0                                                                                                                                                                                                                                           
> -- Check for working C compiler: /usr/bin/cc                                                                                                                                                                                                                                              
> -- Check for working C compiler: /usr/bin/cc -- works                                                                                                                                                                                                                                     
> -- Detecting C compiler ABI info                                                                                                                                                                                                                                                          
> -- Detecting C compiler ABI info - done                                                                                                                                                                                                                                                   
> -- Detecting C compile features                                                                                                                                                                                                                                                           
> -- Detecting C compile features - done                                                                                                                                                                                                                                                    
> -- Check for working CXX compiler: /usr/bin/c++                                                                                              
> -- Check for working CXX compiler: /usr/bin/c++ -- works                                                                                     
> -- Detecting CXX compiler ABI info                                                                                                                                                                                                                                                        
> -- Detecting CXX compiler ABI info - done                                                                                                                                                                                                                                                 
> -- Detecting CXX compile features                                                                                                                                                                                                                                                         
> -- Detecting CXX compile features - done                                                                                                                                                                                                                                                  
> -- Performing Test COMPILER_SUPPORTS_CXX17                                                                                                                                                                                                                                                
> -- Performing Test COMPILER_SUPPORTS_CXX17 - Success                                                                                         
> -- Performing Test COMPILER_SUPPORTS_CXX14                                                                                                                                                                                                                                                
> -- Performing Test COMPILER_SUPPORTS_CXX14 - Success                                                                                         
> -- Performing Test COMPILER_SUPPORTS_CXX11                                                                                                   
> -- Performing Test COMPILER_SUPPORTS_CXX11 - Success                                                                                                                                                                                                                                      
> -- Performing Test COMPILER_SUPPORTS_CXX0X                                                                                                                                                                                                                                                
> -- Performing Test COMPILER_SUPPORTS_CXX0X - Success                                                                                                                                                                                                                                      
> -- Using C++17 compiler                                                                                                                      
> -- Found ament_cmake: 0.9.8 (/home/seulbae/workspace/ros-security/ros2_foxy/install/ament_cmake/share/ament_cmake/cmake)                                                                                                                                                                  
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3")                                                                                                                                                                                         
> -- Using PYTHON_EXECUTABLE: /usr/bin/python3                                                                                                 
> -- Override CMake install command with custom implementation using symlinks instead of copying resources                                                                                                                                                                                  
> -- Found builtin_interfaces: 1.0.0 (/home/seulbae/workspace/ros-security/ros2_foxy/install/builtin_interfaces/share/builtin_interfaces/cmake)                                                                                                                                             
> -- Using all available rosidl_typesupport_c: rosidl_typesupport_introspection_c;rosidl_typesupport_fastrtps_c                                                                                                                                                                             
> -- Found rosidl_adapter: 1.2.1 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake)            
> -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")                                                            
> -- Found FastRTPS: /home/seulbae/workspace/ros-security/ros2_foxy/install/fastrtps/include                                                                                                                                                                                                
> -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_introspection_cpp;rosidl_typesupport_fastrtps_cpp                          
> -- Found rclcpp: 2.3.1 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rclcpp/share/rclcpp/cmake)                                                                                                                                                                                 
> -- Found rmw_implementation_cmake: 1.0.3 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rmw_implementation_cmake/share/rmw_implementation_cmake/cmake)                                                                                                                           
> -- Using RMW implementation 'rmw_fastrtps_cpp' as default                                                                                    
> -- Looking for pthread.h                                                                                                                     
> -- Looking for pthread.h - found                                                                                                             
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD                                                                                                   
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed                                                                                                                                                                                                                                       
> -- Looking for pthread_create in pthreads                                                                                                    
> -- Looking for pthread_create in pthreads - not found                                                                                                                                                                                                                                     
> -- Looking for pthread_create in pthread                                                                                                     
> -- Looking for pthread_create in pthread - found                                                                                             
> -- Found Threads: TRUE                                                                                                                                                                                                                                                                    
> -- Found rmw_fastrtps_cpp: 1.2.5 (/home/seulbae/workspace/ros-security/ros2_foxy/install/rmw_fastrtps_cpp/share/rmw_fastrtps_cpp/cmake)                                                                                                                                                   
> -- Found px4_msgs: 2.0.1 (/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/cmake)               
> -- Found sensor_msgs: 2.0.4 (/home/seulbae/workspace/ros-security/ros2_foxy/install/sensor_msgs/share/sensor_msgs/cmake)                                                                                                                                                                  
> -- Found eigen3_cmake_module: 0.1.1 (/home/seulbae/workspace/ros-security/ros2_foxy/install/eigen3_cmake_module/share/eigen3_cmake_module/cmake)                                                                                                                                          
> -- fastrtpsgen found in /usr/local/bin                                                                                                                                                                                                                                                    
> openjdk version "11.0.11" 2021-04-20                                                                                                                                                                                                                                                      
> OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)                                                                                                                                                                                                                       
> OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)                                                        
> -- fastrtpsgen version 1.0.4                                                                                                                                                                                                                                                              
> -- px4_msgs message dir under /home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg              
> -- IDL definitions under /home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg                                                                                                                                                                
> -- Retrieving list of msgs to send...                                                                                                                                                                                                                                                     
> -- List of msgs to send: DebugArray, DebugKeyValue, DebugValue, DebugVect, OffboardControlMode, OpticalFlow, PositionSetpoint, PositionSetpointTriplet, TelemetryStatus, Timesync, TrajectoryWaypoint, VehicleCommand, VehicleLocalPositionSetpoint, VehicleTrajectoryWaypoint, OnboardCom
> puterStatus, TrajectoryBezier, VehicleTrajectoryBezier, VehicleMocapOdometry, VehicleVisualOdometry, TrajectorySetpoint                                                                                                                                                                   
> -- Retrieving list of msgs to receive...                                                                                                     
> -- List of msgs to receive: InputRc, SatelliteInfo, SensorCombined, Timesync, TrajectoryWaypoint, VehicleAttitude, VehicleControlMode, VehicleLocalPosition, VehicleOdometry, VehicleStatus, CollisionConstraints, VehicleAngularVelocity                                                 
> -- Configuring done                                                                                                                                                                                                                                                                       
> -- Generating done                                                                                                                           
> -- Build files have been written to: /home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/build/px4_ros_com  
> ```

Something is not right on the above: why are you building the Firmware inside you colcon workspace?

**Comment by squizz617** [comment]
> Something is not right on the above: why are you building the Firmware inside your colcon workspace?
I don't get the question; what do you mean by the Frimware? I have my own ros2 built from source, and just trying to build the bridge, i.e., `px4_msgs` and `px4_ros_com`, separately.

**Comment by TSC21** [comment]
> > Something is not right on the above: why are you building the Firmware inside your colcon workspace?
> 
> I don't get the question; what do you mean by the Frimware? I have my own ros2 built from source, and just trying to build the bridge, i.e., `px4_msgs` and `px4_ros_com`, separately.

I am sorry I misread the log you showed,

> BTW, here's the dump of stdout. This might help finding the cause?
What do you mean with a dump? What you get from the console is the output of the build. have a look at what CI outputs for example: https://github.com/PX4/px4_ros_com/pull/92/checks?check_run_id=2849923419.

**Comment by squizz617** [comment]
> What do you mean with a dump? What you get from the console is the output of the build. have a look at what CI outputs for example: https://github.com/PX4/px4_ros_com/pull/92/checks?check_run_id=2849923419.

Attatched above literally is the build output of `colcon build --symlink-install` command, after including the header:
```
$ cd px4_ros_com_ros2
$ colcon build --symlink-install
$ cat log/latest_build/px4_ros_com/stdout.log
```

**Comment by TSC21** [comment]
Try https://github.com/PX4/px4_ros_com/blob/master/scripts/build_ros2_workspace.bash#L124

**Comment by squizz617** [comment]
Okay, let me try to be clear.

Regardless of how I build - either using the provided `build_ros2_workspace.bash` script, or manually specifying the ros2 workspace and running `colcon build` - the build fails at `px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp`, as it cannot resolve `PRIu32` and `PRIu16` macros. The exact same error messages are given, as shown below:
```
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp: In member function ‘ssize_t Transport_node::read(uint8_t*, char*, size_t)’:
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:153:99: error: expected ‘)’ before ‘PRIu32’
  153 |   if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓↓ %" PRIu32 ")\033[0m\n", msg_start_pos);
      |                    ~                                                                              ^~~~~~~
      |                                                                                                   )
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:153:97: warning: spurious trailing ‘%’ in format [-Wformat=]
  153 |   if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓↓ %" PRIu32 ")\033[0m\n", msg_start_pos);
      |                                                                                                 ^
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:153:21: warning: too many arguments for format [-Wformat-extra-args]
  153 |   if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓↓ %" PRIu32 ")\033[0m\n", msg_start_pos);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:181:97: error: expected ‘)’ before ‘PRIu32’
  181 |    if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓ %" PRIu32 ")\033[0m\n", msg_start_pos);
      |                     ~                                                                           ^~~~~~~
      |                                                                                                 )
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:181:95: warning: spurious trailing ‘%’ in format [-Wformat=]
  181 |    if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓ %" PRIu32 ")\033[0m\n", msg_start_pos);
      |                                                                                               ^
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:181:22: warning: too many arguments for format [-Wformat-extra-args]
  181 |    if (debug) printf("\033[1;33m[ micrortps_transport ]\t                                (↓ %" PRIu32 ")\033[0m\n", msg_start_pos);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:197:67: error: expected ‘)’ before ‘PRIu16’
  197 |   if (debug) printf("\033[0;31m[ micrortps_transport ]\tBad CRC %" PRIu16 " != %" PRIu16 "\t\t(↓ %lu)\033[0m\n", read_crc, calc_crc, (unsigned long)(header_size + payload_len));
      |                    ~                                              ^~~~~~~
      |                                                                   )
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:197:65: warning: spurious trailing ‘%’ in format [-Wformat=]
  197 |   if (debug) printf("\033[0;31m[ micrortps_transport ]\tBad CRC %" PRIu16 " != %" PRIu16 "\t\t(↓ %lu)\033[0m\n", read_crc, calc_crc, (unsigned long)(header_size + payload_len));
      |                                                                 ^
/home/seulbae/workspace/ros-security/targets/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_transport.cpp:197:21: warning: too many arguments for format [-Wformat-extra-args]
  197 |   if (debug) printf("\033[0;31m[ micrortps_transport ]\tBad CRC %" PRIu16 " != %" PRIu16 "\t\t(↓ %lu)\033[0m\n", read_crc, calc_crc, (unsigned long)(header_size + payload_len));
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/micrortps_agent.dir/build.make:576: CMakeFiles/micrortps_agent.dir/src/micrortps_agent/microRTPS_transport.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/micrortps_agent.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< px4_ros_com [2min 18s, exited with code 2]

Summary: 1 package finished [7min 32s]
  1 package failed: px4_ros_com
  1 package had stderr output: px4_ros_com

```

Including the header (what this PR does), the project builds fine, regardless of the method (running the script or manual).

**Comment by TSC21** [comment]
@squizz617 I understand. But need to add headers needs to be justified. The entire CI pipeline builds with Ubuntu 18.04 and 20.04, from ROS2 Dashing to ROS2 Rolling. I myself can build it without any issues. So the first thing would be dig why do you need this in the first place.

**Comment by TSC21** [comment]
@squizz617 I am sorry. I just now saw that the latest commit to the repo actually broke this. Although, do you mind issuing this PR against https://github.com/PX4/PX4-Autopilot instead, where the source templates live? They get delpioyed from there so they need to be updated there. Thank you!

**Comment by TSC21** [comment]
Bringing the fix here: https://github.com/PX4/PX4-Autopilot/pull/17782. Added you as a co-author. Thanks!
